# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Net-Jabber-Loudmouth
version:      0.07
version_from: pm/Loudmouth.pm
installdirs:  site
requires:
    Glib:                          1.093

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
